"""remove test_unmoderated table

Revision ID: 1729e337ab9f
Revises: 3af5c611aa38
Create Date: 2025-05-14 15:36:52.491792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1729e337ab9f'
down_revision = '3af5c611aa38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('test_unmoderated')
    op.drop_table('test_results')
    op.drop_table('test_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wrong_1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wrong_2', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wrong_3', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='test_questions_material_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_questions_pkey')
    )
    op.create_table('test_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='test_results_test_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='test_results_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_results_pkey')
    )
    op.create_table('test_unmoderated',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wrong_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wrong_2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wrong_3', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='test_unmoderated_material_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_unmoderated_pkey')
    )
    op.drop_table('test_question')
    op.drop_table('test_result')
    # ### end Alembic commands ###
