"""Add image_path column to orders table

Revision ID: 28be85a8ef65
Revises: 2b60b75acdb0
Create Date: 2025-05-29 11:21:12.017631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28be85a8ef65'
down_revision = '2b60b75acdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.alter_column('orders', 'number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('orders_number_key', 'orders', type_='unique')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint('orders_number_key', 'orders', ['number'])
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('orders', 'number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('orders', 'image_path')
    # ### end Alembic commands ###
