"""Add test_unmoderated table

Revision ID: 3af5c611aa38
Revises: c52868bebd90
Create Date: 2025-05-14 15:13:38.312018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af5c611aa38'
down_revision = 'c52868bebd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_unmoderated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('wrong_1', sa.Text(), nullable=False),
    sa.Column('wrong_2', sa.Text(), nullable=False),
    sa.Column('wrong_3', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_unmoderated')
    # ### end Alembic commands ###
