"""remove email from users

Revision ID: f438645f5689
Revises: faa69635eb98
Create Date: 2025-05-23 13:06:48.844894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f438645f5689'
down_revision = 'faa69635eb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_question_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_given', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_question_results')
    op.drop_table('test_results')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('test_end_date')
        batch_op.drop_column('test_start_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('test_results',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('test_results_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='test_results_test_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='test_results_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_results_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('test_question_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_given', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], name='test_question_results_question_id_fkey'),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], name='test_question_results_test_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_question_results_pkey')
    )
    op.drop_table('test_question_result')
    op.drop_table('test_result')
    # ### end Alembic commands ###
