"""Add test_id to TestResult model

Revision ID: faa69635eb98
Revises: cfe5f14d63cc
Create Date: 2025-05-23 11:35:52.885518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa69635eb98'
down_revision = 'cfe5f14d63cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tests', ['test_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###
