"""Update phone_number field in User model

Revision ID: ff3339e19f4d
Revises: add_test_dates
Create Date: 2025-05-27 17:41:05.518930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3339e19f4d'
down_revision = 'add_test_dates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
