name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "portalabrams"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        
    - name: Run migrations
      run: |
        # Установка Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh
        
        # Логин через API ключ
        echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token
        
        # Запуск миграций
        heroku run flask db upgrade --app portalabrams 